/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package squeakyclean;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAnIdentifier() {
        String identifier = "Testing";
        assertNotNull("app should have a identifier", SqueakyClean.clean(identifier));
    }
}
